---
title: "Pilot of Experiment 1"
author: "Simon Stephan"
output:  
  html_document:
    number_sections: true
    toc: true  
    collapsed: false
    toc_float: true
    smooth_scroll: false
    toc_depth: 3
---

```{r setup, include=FALSE}
# packages
library(ez)
library(reshape2)
library(reshape)
library(ggplot2)
library(plyr)
library(pastecs)
library(ez)
library(data.table)
library(tidyverse) 

library(showtext)


font_add_google("Poppins", "Poppins")
font_add_google("Roboto Mono", "Roboto Mono")
showtext_auto()
```


```{r}
tdata <- read.delim("pilot_data_strength_10.txt", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)


N <- table(tdata$Strength, tdata$Level)
N
N_gov <- N[1]
N_pers <- N[2]

```


# Subject demographics

```{r}
# demographics 

tdata_age <- tdata 

min(tdata_age$Age)
max(tdata_age$Age)
mean(tdata_age$Age)
sd(tdata_age$Age)

# 1 = male, 2 = female, 3 = other
table(tdata$Sex)
```

1 = male, 2 = female, 3 = non-binary


# Analysis

```{r, echo = FALSE}
# reorder factor 

# to create chart, the data must be in long format and only contain the relevant dependent variables

# 1. make a subset with only the relevant dvs 

tdata_sub <- subset(tdata, select = c(1:8,12))


# 2. reshape into long format 
tdata_long <- tdata_sub %>% gather(variable, value, 7:8)


tdata_long$variable <- factor(tdata_long$variable, levels = c("rating_stable", "rating_unstable"), 
                          labels = c("stable cause", "unstable cause"))

#tdata_long$Strength <- factor(tdata_long$Strength, levels = c("ten", "fifty", "ninety"), 
#                              labels = c("0.10", "0.50", "0.90"))

tdata_long$Strength <- factor(tdata_long$Strength, levels = c("ten"), 
                              labels = c("0.10"))


tdata_long$value <- tdata_long$value * 0.01 # Recode DV so that values range from 0 to 1

```

## Graphs

```{r}
myTheme <- theme(plot.title = element_text(face="bold", size = 22),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold", size = 20),
        axis.text.x = element_text(size = 12, angle = 0), 
        axis.text.y = element_text(size = 16, angle = 0),
        legend.text = element_text(size = 18),
        legend.title = element_text(face = "bold", size = 18),
        strip.text.x = element_text(size = 18),
        #panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line.x = element_line(colour = "black"), 
        axis.line.y = element_line(colour = "black"),
        axis.text = element_text(colour ="black"), 
        axis.ticks = element_line(colour ="black"))

tdata_sub <- tdata_long


library(see)
## first, turn sID into a factor
tdata_sub$sID <- factor(tdata_sub$sID)

pd <- position_dodge(width = 0.3)

tdata_sub$valueJitter <- jitter(tdata_sub$value, factor = 1, amount = 0.04)

theme_set(theme_light(base_size = 20, base_family = "Poppins"))

# new labes for the facets 

g <- ggplot(tdata_sub, aes(x=variable, y=valueJitter, group = sID)) +
  guides(fill=FALSE)+
  facet_grid( ~ Level)+
  #ggtitle("Subjects' causal srength ratings") +
  scale_y_continuous(limits = c(-0.05, 1.05), breaks=seq(0, 1, 0.1), expand = c(0,0)) +
  #scale_x_discrete(labels=c("Single-effect \ncause", "Common \ncause", "No \ncause")) +
  #stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha =0.5) +
  geom_violinhalf(aes(y = value, group = variable, fill = variable), color = NA, position=position_dodge(1), alpha = 0.2)+
  geom_line(position = pd, color = "black", size = 1, alpha=0.04) +
  geom_point(aes(color = variable), position = pd, alpha = 0.2) +
  stat_summary(aes(y = value,group=1), fun.data = mean_cl_boot, geom = "errorbar", width = 0, size = 1) +
  stat_summary(aes(y = value,group=1), fun.y=mean, colour="black", geom="line",group=1, size = 1.5, linetype = "solid", alpha = 1)+
  stat_summary(aes(y = value,group=1, fill = variable), fun.y=mean, geom="point", color = "black", shape = 22, size = 5, group=1, alpha = 1)+
  stat_summary(aes(y = value,group=1), fun.y=median, geom="point", color = "black", shape = 3, size = 4, group=1, alpha = 1, 
               position = position_dodge(width = 0.5))+
  labs(x = "Type of Cause", y = "Willingness to choose this cause") +
  scale_color_manual(name = "Entity",values=c("#fc9272", "#3182bd"))+
  scale_fill_manual(name = "Entity",values=c("#fc9272", "#3182bd"))+
  theme(legend.position = "none")+
  myTheme
g


#ggsave("results_lines.svg",width=8,height=6)
#ggsave("results_lines.pdf",width=8,height=6)
```




## ANOVA

```{r, echo = FALSE, warning = FALSE, message = FALSE}

################################################################################################################
##################################### Statistical Analyses #####################################################
################################################################################################################
library(pastecs)
library(lme4)
library(nlme)
library(ez)


library(afex)
library(emmeans)

a1 <- aov_car(value ~ variable*Level + Error(sID/(variable)), tdata_sub)
a1


```
## Contrasts


```{r}
# follow-up analysis 

ls1 <- lsmeans(a1, c("variable", "Level")) # joint evaluation (basically gives the same table)
ls1
```




```{r}
############### 
# a conditional analysis 

ls2 <- lsmeans(a1, c("variable", "Level")) # group means by between-condition
ls2

interaction <- emmeans(a1, ~ variable|Level)
pairs(interaction, adjust = "none")

# simple main effects 
t <- pairs(ls2, adjust="none") # compares rep-measure differences separately for each between-factor level
#t

confint(t, level = 0.95)
```
## Difference plots

Make a difference plot: 


```{r}
# Government
#t <- qt(0.975, 29, lower.tail = TRUE, log.p = FALSE)
#t

effect <- "Mdiff"
Mdiff <- 0.2713
CI_low <- 0.1726
CI_up <- 0.36998

Mdiff
CI_low
CI_up



# Plot 

myTheme <- theme(plot.title = element_text(face="bold", size = 22),
        axis.title.x = element_text(face = "bold", size = 20),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 18, angle = 0), 
        axis.text.y = element_text(size = 40, angle = 0),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 22),
        strip.text.x = element_text(size = 10),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(), 
        #panel.background = element_blank(), 
        axis.line.x = element_line(colour = "black"), 
        axis.line.y = element_line(colour = "black"),
        axis.text = element_text(colour ="black"), 
        axis.ticks = element_line(colour ="black"))

theme_set(theme_light(base_size = 30, base_family = "Poppins"))



barchart <- ggplot()+
  myTheme+
  #guides(fill=FALSE)+
  #facet_wrap(~Latency + SampleSize, ncol=2)+
  #ggtitle("Mean difference (95% CI)") +
  #coord_cartesian(ylim=c(-0.1,2)) + 
  scale_y_continuous(limits = c(-0.1, 1), breaks=seq(-0.1, 1, 0.2), expand = c(0,0)) +
  scale_x_discrete(labels=c("r")) +
  #annotate("rect", xmin=1.7, xmax=2.3, ymin=0.95, ymax=1.05, color="#31a354", fill = "white", size = 1) +
  #stat_summary(fun.y=mean, colour="grey20", geom="point", shape = 21, size = 3)+
  #stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black")+
  #stat_summary(fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  #geom_jitter(width = 0.3, height = 0.02, alpha = 0.6, colour = "red") +
  #ggtitle("Means (95% bootstr. CIs)") +
  #theme(axis.text.x = element_text(size = 10, angle = 0, hjust = 0.5))+
  labs(x= "", y = "Mean change") +
  #scale_color_manual(values=c("#005083",  "#f0b64d"))# +
  #scale_fill_manual(values=c("#969696",  "#969696"))
  #annotate("point", x = 1, y = 100, colour = "firebrick", size = 2)+
  #annotate(xmin = -Inf, xmax = Inf, ymin = 4.77-1.96*0.297, ymax = 4.77+1.96*0.297, geom = "rect", alpha = 0.2, fill = "firebrick")+
  #annotate(xmin = -Inf, xmax = Inf, ymin = 5.02-1.96*0.372, ymax = 5.02+1.96*0.372, geom = "rect", alpha = 0.2, fill = "blue")+
  #annotate(geom = "hline",yintercept = 100, y = 100, color = "red")+
  annotate("pointrange", x = 1, y = Mdiff, ymin = CI_low, ymax = CI_up, colour = "black", size = 2, shape = 24, fill = "darkgrey")+
  #annotate("pointrange", x = 2, y = 5.02, ymin = 5.02-1.96*0.372, ymax = 5.02+1.96*0.372, colour = "blue", size = 0.8, shape = 15)+
  #annotate("text", x = 0.5, y = 2.6, family = "Poppins", size = 6, color = "gray20", label = "Impfeffekt")+
  #geom_curve(aes(x = 0.5, y = 3, xend = 0.9, yend = 4),arrow = arrow(length = unit(0.03, "npc")),color = "gray20", curvature = +0.2)+
  #annotate("text", x = 1.8, y = 2.6, family = "Poppins", size = 6, color = "gray20", label = "Dosierungseffekt")+
  #geom_curve(aes(x = 1.8, y = 3, xend = 2, yend = 4),arrow = arrow(length = unit(0.03, "npc")),color = "gray20", curvature = +0.2)+
  annotate(geom = "hline",yintercept = 0, y = 0, color = "red", size = 1.2)+
  theme(plot.background = element_rect(
    fill = "white",
    colour = "white",
    size = 1
  ))


barchart

#ggsave("delta_gov.svg",width=2.5,height=4)
#ggsave("delta_gov.pdf",width=2.5,height=4)
```


```{r}
# Government
#t <- qt(0.975, 29, lower.tail = TRUE, log.p = FALSE)
#t

effect <- "Mdiff"
Mdiff <- 0.0752
CI_low <- -0.0205  
CI_up <- 0.17100

Mdiff
CI_low
CI_up



# Plot 

myTheme <- theme(plot.title = element_text(face="bold", size = 22),
        axis.title.x = element_text(face = "bold", size = 20),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 18, angle = 0), 
        axis.text.y = element_text(size = 40, angle = 0),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 22),
        strip.text.x = element_text(size = 10),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(), 
        #panel.background = element_blank(), 
        axis.line.x = element_line(colour = "black"), 
        axis.line.y = element_line(colour = "black"),
        axis.text = element_text(colour ="black"), 
        axis.ticks = element_line(colour ="black"))

theme_set(theme_light(base_size = 30, base_family = "Poppins"))



barchart <- ggplot()+
  myTheme+
  #guides(fill=FALSE)+
  #facet_wrap(~Latency + SampleSize, ncol=2)+
  #ggtitle("Mean difference (95% CI)") +
  #coord_cartesian(ylim=c(-0.1,2)) + 
  scale_y_continuous(limits = c(-0.1, 1), breaks=seq(-0.1, 1, 0.2), expand = c(0,0)) +
  scale_x_discrete(labels=c("r")) +
  #annotate("rect", xmin=1.7, xmax=2.3, ymin=0.95, ymax=1.05, color="#31a354", fill = "white", size = 1) +
  #stat_summary(fun.y=mean, colour="grey20", geom="point", shape = 21, size = 3)+
  #stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black")+
  #stat_summary(fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  #geom_jitter(width = 0.3, height = 0.02, alpha = 0.6, colour = "red") +
  #ggtitle("Means (95% bootstr. CIs)") +
  #theme(axis.text.x = element_text(size = 10, angle = 0, hjust = 0.5))+
  labs(x= "", y = "Mean change") +
  #scale_color_manual(values=c("#005083",  "#f0b64d"))# +
  #scale_fill_manual(values=c("#969696",  "#969696"))
  #annotate("point", x = 1, y = 100, colour = "firebrick", size = 2)+
  #annotate(xmin = -Inf, xmax = Inf, ymin = 4.77-1.96*0.297, ymax = 4.77+1.96*0.297, geom = "rect", alpha = 0.2, fill = "firebrick")+
  #annotate(xmin = -Inf, xmax = Inf, ymin = 5.02-1.96*0.372, ymax = 5.02+1.96*0.372, geom = "rect", alpha = 0.2, fill = "blue")+
  #annotate(geom = "hline",yintercept = 100, y = 100, color = "red")+
  annotate("pointrange", x = 1, y = Mdiff, ymin = CI_low, ymax = CI_up, colour = "black", size = 2, shape = 24, fill = "darkgrey")+
  #annotate("pointrange", x = 2, y = 5.02, ymin = 5.02-1.96*0.372, ymax = 5.02+1.96*0.372, colour = "blue", size = 0.8, shape = 15)+
  #annotate("text", x = 0.5, y = 2.6, family = "Poppins", size = 6, color = "gray20", label = "Impfeffekt")+
  #geom_curve(aes(x = 0.5, y = 3, xend = 0.9, yend = 4),arrow = arrow(length = unit(0.03, "npc")),color = "gray20", curvature = +0.2)+
  #annotate("text", x = 1.8, y = 2.6, family = "Poppins", size = 6, color = "gray20", label = "Dosierungseffekt")+
  #geom_curve(aes(x = 1.8, y = 3, xend = 2, yend = 4),arrow = arrow(length = unit(0.03, "npc")),color = "gray20", curvature = +0.2)+
  annotate(geom = "hline",yintercept = 0, y = 0, color = "red", size = 1.2)+
  theme(plot.background = element_rect(
    fill = "white",
    colour = "white",
    size = 1
  ))


barchart

#ggsave("delta_pers.svg",width=2.5,height=4)
#ggsave("delta_pers.pdf",width=2.5,height=4)
```


## Standardized effect sizes

What Cohen's d is this? 


```{r}
# Level = government

dat <- subset(tdata_sub, Level == "government")


# since we have a repeated-meausres design, we now need the correlations of the ratings
library(dplyr) # for pipe operator
t <- subset(tdata, Level == "government")
r <- cor(t$rating_stable, t$rating_unstable)
r


# now compute ES and SE and CI of it
# using the esc package because it gives SE of the ES directly
library(esc)

# get means and sds
m1 <- dat %>%
          filter(variable == "stable cause")%>%
          summarize(Mean1 = mean(value))

sd1 <- dat %>%
          filter(variable == "stable cause")%>%
          summarize(SD1 = sd(value))


m2 <- dat %>%
          filter(variable == "unstable cause")%>%
          summarize(Mean2 = mean(value))

sd2 <- dat %>%
          filter(variable == "unstable cause")%>%
          summarize(SD2 = sd(value))



d <- esc_mean_sd(
  grp1m = m1[,1], grp1sd = sd1[,1], grp1n = length(dat$sID)/2,
  grp2m = m2[,1], grp2sd = sd2[,1], grp2n = length(dat$sID)/2,
  r = r,
  es.type = "d"
)
d

d$ci.lo
d$ci.hi

d_ci <- (d$ci.hi - d$ci.lo)/2
d_ci
```

```{r}
# Level = government

dat <- subset(tdata_sub, Level == "personal")


# since we have a repeated-meausres design, we now need the correlations of the ratings
library(dplyr) # for pipe operator
t <- subset(tdata, Level == "personal")
r <- cor(t$rating_stable, t$rating_unstable)
r


# now compute ES and SE and CI of it
# using the esc package because it gives SE of the ES directly
library(esc)

# get means and sds
m1 <- dat %>%
          filter(variable == "stable cause")%>%
          summarize(Mean1 = mean(value))

sd1 <- dat %>%
          filter(variable == "stable cause")%>%
          summarize(SD1 = sd(value))


m2 <- dat %>%
          filter(variable == "unstable cause")%>%
          summarize(Mean2 = mean(value))

sd2 <- dat %>%
          filter(variable == "unstable cause")%>%
          summarize(SD2 = sd(value))



d <- esc_mean_sd(
  grp1m = m1[,1], grp1sd = sd1[,1], grp1n = length(dat$sID)/2,
  grp2m = m2[,1], grp2sd = sd2[,1], grp2n = length(dat$sID)/2,
  r = r,
  es.type = "d"
)
d

d$ci.lo
d$ci.hi

d_ci <- (d$ci.hi - d$ci.lo)/2
d_ci
```



## Cluster Analysis 

```{r}

data_cluster <- tdata[c(1:8)]

# append absolut deviations as new columns
data_cluster$Delta_Rating <- data_cluster$rating_stable - data_cluster$rating_unstable



crit = 0

data_cluster$Change[data_cluster$Delta_Rating > crit] <- "Stable Cause"
data_cluster$Change[data_cluster$Delta_Rating >= -crit & data_cluster$Delta_Rating <= crit] <- "Indifference"
data_cluster$Change[data_cluster$Delta_Rating < -crit] <- "Unstable Cause"



cluster <- data_cluster %>% count(Level, Strength, Change)
cluster
# now append the clustering results to the main data frame 
data_cluster <- subset(data_cluster, select = c(1,10))

tdata_sub <- merge(tdata_sub, data_cluster, by = c("sID"))

```

```{r}
# create a summary dataset that also contains the percentages
plotdata_between <- tdata_sub %>%
  group_by(Level, Change) %>%
  summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct))
```

### Proportion tests 
Used to get the CIs of the proportion estimates.

```{r}
# append CI of the proportions 
cases <- cluster$n
t <- prop.test(cases[1],N_gov,correct=FALSE) # get CI for Invariance government
CI_gov_In_min <- t$conf.int[1]
CI_gov_In_max <- t$conf.int[2]


t <- prop.test(cases[2],N_gov,correct=FALSE) # get CI for Invariance government
CI_gov_St_min <- t$conf.int[1]
CI_gov_St_max <- t$conf.int[2]

t <- prop.test(cases[3],N_gov,correct=FALSE) # get CI for Invariance government
CI_gov_USt_min <- t$conf.int[1]
CI_gov_USt_max <- t$conf.int[2]



t <- prop.test(cases[4],N_pers,correct=FALSE) # get CI for Invariance government
CI_pers_In_min <- t$conf.int[1]
CI_pers_In_max <- t$conf.int[2]

t <- prop.test(cases[5],N_pers,correct=FALSE) # get CI for Invariance government
CI_pers_St_min <- t$conf.int[1]
CI_pers_St_max <- t$conf.int[2]


t <- prop.test(cases[6],N_pers,correct=FALSE) # get CI for Invariance government
CI_pers_USt_min <- t$conf.int[1]
CI_pers_USt_max <- t$conf.int[2]

CI_low <- c(CI_gov_In_min, CI_gov_St_min, CI_gov_USt_min, CI_pers_In_min, CI_pers_St_min, CI_pers_USt_min)
CI_up <- c(CI_gov_In_max, CI_gov_St_max, CI_gov_USt_max, CI_pers_In_min, CI_pers_St_max, CI_pers_USt_max)

plotdata_between$CI_low <- CI_low
plotdata_between$CI_up <- CI_up

```


```{r}
library(scales)
theme_set(theme_light(base_size = 10, base_family = "Poppins"))

plotdata <- plotdata_between
#plotdata <- subset(plotdata, Change != "Invariance")

g<- ggplot(plotdata, 
       aes(x = Level,
           y = pct,
           fill = Change)) +
  #facet_grid( ~ Level)+
  geom_bar(stat = "identity",
           position = "dodge") +
  scale_y_continuous(limits = seq(0, 2),
                     breaks = seq(0, 1, .25),
                     expand = c(0,0),
                     label = percent) +
  coord_cartesian(xlim =c(1, 2), ylim = c(0, 1.1))+
  #coord_cartesian(clip = "off")+
  #geom_text(aes(label = lbl), 
  #          size = 4, 
  #          position = position_stack(vjust = 0.5)) +
  geom_text(aes(label = lbl), 
            size = 4, 
            position = position_dodge(width = .9),
            vjust = +4.5) +
  geom_errorbar(aes(ymin=CI_low, ymax=CI_up), width=.0,
                 position=position_dodge(.9)) +
  scale_fill_brewer(palette = "Pastel1") +
  scale_fill_manual(values=c("#bdbdbd","#fc9272","#3182bd")) +
  labs(y = "Percentage", 
       fill = "Preference",
       x = "Context (Decision Level)",
       title = "Average causal strength = 0.10")+
  #annotate(geom = "hline",yintercept = 0.5, y = 0.5, color = "black", size = 1, linetype='dotted')+
  #annotate("pointrange", x = c(1,2), y = 1 - plotdata$pct, 
  #         ymin = 1 - plotdata$pct - plotdata$CI, 
  #         ymax = 1- plotdata$pct + plotdata$CI, 
  #         colour = "black", size = 0.8, shape = 22, fill = "lightblue", fatten = 1)+
  #annotate("text", x = 1.25, y = Inf, label = "p < .001", size = 4, vjust = 1.6)+
  #annotate("text", x = 2.35, y = Inf, label = "p = .09", size = 4, vjust = 4)+
  theme(legend.position = "right", axis.title = element_text(size = 12), axis.text = element_text(size = 10, color = "black"),
        legend.text = element_text(size = 10),legend.title = element_text(size = 12))+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

g
#ggsave("selections_Dim.pdf",width=5,height=4)
#ggsave("selections_Dim.svg",width=5,height=4)
```




